<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZSEc6NK\AppTestDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZSEc6NK/AppTestDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerZSEc6NK.legacy');

    return;
}

if (!\class_exists(AppTestDebugProjectContainer::class, false)) {
    \class_alias(\ContainerZSEc6NK\AppTestDebugProjectContainer::class, AppTestDebugProjectContainer::class, false);
}

return new \ContainerZSEc6NK\AppTestDebugProjectContainer(array(
    'container.build_hash' => 'ZSEc6NK',
    'container.build_id' => 'c955b49a',
    'container.build_time' => 1521024949,
));
